version: "3"
services:
  refactoring-comment-slack:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: refactoring-comment-slack
    container_name: refactoring-comment-slack-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
